
FROM node:20-slim AS build
WORKDIR /app
COPY ui/package.json ui/package-lock.json* ui/yarn.lock* ./
RUN npm i --force || yarn || true
COPY ui .
RUN npm run build || yarn build
FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
